# Generated by Django 5.2.5 on 2025-08-13 15:50

from django.db import migrations, models

import utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    utils.fields.ULIDField(
                        default=utils.fields.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
    ]
