services:
  web:
    build:
      context: .
      target: production
    container_name: tasks
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-0}
      - SECRET_KEY=${SECRET_KEY:?set in .env}
      - ALLOWED_HOSTS=${DOMAIN}
      - CSRF_TRUSTED_ORIGINS=https://${DOMAIN}
      - DATABASE_URL=postgresql://tasks:${POSTGRES_PASSWORD:?set in .env}@database:5432/tasks
      - DJANGO_SETTINGS_MODULE=config.settings
      - SECURE_SSL_REDIRECT=${SECURE_SSL_REDIRECT:-True}
    volumes:
      - staticfiles:/app/staticfiles
    networks:
      web:
        aliases:
          - tasks
    ports:
      - "8000:8000"

volumes:
  staticfiles:

networks:
  web:
    external: true
