services:
  web:
    build:
      context: .
      target: development
    container_name: tasks
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://tasks:tasks@db:5432/tasks
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:15-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=tasks
      - POSTGRES_PASSWORD=tasks
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasks"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data:
