# Generated by Django 5.2.5 on 2025-08-15 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timeblocks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeblock",
            old_name="notes",
            new_name="log",
        ),
    ]
