# Generated by Django 5.2.5 on 2025-08-15 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeblocks", "0002_rename_notes_timeblock_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeblock",
            name="started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
